### ISSUE TITLE
Inconsistent formatting

### ISSUE THREAD

**Issue by jim-rosales** [mfb16/Colmar-Academy#4]
It's important to keep your formatting consistent throughout your file as it helps improve its readability.

For example for this section you code was written in the following way:
```CSS
  .container-2 { /** Note the space before the closing { **/
      width: 40%;
      display: flex;
      flex-direction: column; /** Note the space after the : character **/
    }

/** All these rules also have two spaces added to the front as well **/
  .update{
      display: flex;
      padding: 0 0 16px 16px;
    }

  .update:last-child{ /** Note that a space was not added before the { **/
      background-color:lightgray; /** Note that a space was not added after the : character **/
      padding-top: 16px;
    }
```

For example, the rules below follow consistent formatting throughout:
```CSS
/** All the rules no longer are indented two spaces throughout. **/
.container-2 {
  width: 40%;
  display: flex;
  flex-direction: column; 
}

/** All these rules also have two spaces added to the front as well **/
.update {
  display: flex;
  padding: 0 0 16px 16px;
}

.update:last-child {
  /** Note the use of soft tabs (2 spaces) for indentation **/
  background-color: lightgray; 
  padding-top: 16px;
}
```

This [style guide](https://github.com/airbnb/css) has excellent guidelines for formatting CSS rules correctly.

https://github.com/mfb16/Colmar-Academy/blob/c6afb505e10e5e3aa1d6d507ba1cd0d7288ff1bf/resources/css/style.css#L210-L224
